apiVersion: v1
kind: Service
metadata:
  name: externalapp
  namespace: nginx
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 3100  # Port that the service will be accessed on within the cluster
---
apiVersion: v1
kind: Endpoints
metadata:
  name: externalapp
  namespace: nginx
subsets:
  - addresses:
      - ip: 192.168.70.33  # External IP address
    ports:
      - port: 3100  # External port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: externalapp-ingress
  namespace: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: logs-auth.thetmg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: externalapp
            port:
              number: 3100
  tls:
    - secretName: wildssl
