---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-proxy
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: nginxssl
      port: 443
      protocol: TCP
      targetPort: 443
